### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by jmarkgraf** [mberneaud/DataScienceAssignment2#3]
Hi Malte,

I tried to play a bit with the title, but didn't manage to create a nice title including our institutional affiliation and the course title  (etc.). Do you happen to know how to do that?

**Comment by mberneaud** [comment]
Edit: I saw that you already figured out a way to add  our affiliation, so I just added the course title as a subtitle on top of that. However, the PDF won't render on my computer because pandoc does not find font needed to render the document. I assume this is some kind of compatibility issue between Linux and OSX, so if it renders for you, we are in the clear for the most part while I figure out a way to resolve this issue for me.
